'use client';

import { useLocale } from 'next-intl';
import type { LucideIcon, LucideProps } from 'lucide-react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowDown,
  ArrowUp,
  BarChart3,
  Beaker,
  Bell,
  BellDot,
  BellRing,
  Bookmark,
  Calculator,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  BookOpen,
  Copy,
  CreditCard,
  FileText,
  Droplet,
  Download,
  Clock,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Filter,
  Gauge,
  Grid3X3,
  Heart,
  HelpCircle,
  Home,
  Image as ImageIcon,
  ImageOff,
  List,
  Instagram,
  Loader2,
  LogOut,
  Lock,
  Gift,
  Mail,
  PackagePlus,
  PackageSearch,
  Pen,
  Printer,
  RefreshCw,
  Sparkles,
  RefreshCcw,
  Zap,
  Menu,
  MessageCircle,
  Mic,
  Minus,
  Moon,
  Package,
  Smartphone,
  Phone,
  Plus,
  Play,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShieldCheck,
  ShoppingCart,
  Star,
  Users,
  WifiOff,
  ThumbsDown,
  ThumbsUp,
  Sun,
  Tag,
  Thermometer,
  Trash2,
  Truck,
  Twitter,
  Upload,
  User,
  X,
  Youtube,
  ZoomIn,
  ZoomOut,
  Maximize,
  Minimize,
} from 'lucide-react';
import { forwardRef } from 'react';

import { cn } from '@/lib/utils';
import { ICON_SIZES, type Size } from './variants';

const iconRegistry = {
  activity: Activity,
  alert: AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-down': ArrowDown,
  'arrow-up': ArrowUp,
  'bar-chart-3': BarChart3,
  beaker: Beaker,
  bell: Bell,
  'bell-dot': BellDot,
  'bell-ring': BellRing,
  bookmark: Bookmark,
  calculator: Calculator,
  calendar: Calendar,
  cart: ShoppingCart,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  close: X,
  copy: Copy,
  'external-link': ExternalLink,
  'credit-card': CreditCard,
  droplet: Droplet,
  edit: Edit,
  eye: Eye,
  'eye-off': EyeOff,
  facebook: Facebook,
  filter: Filter,
  gauge: Gauge,
  grid: Grid3X3,
  clock: Clock,
  heart: Heart,
  help: HelpCircle,
  home: Home,
  image: ImageIcon,
  'image-off': ImageOff,
  instagram: Instagram,
  loader: Loader2,
  'loader-2': Loader2,
  logout: LogOut,
  lock: Lock,
  maximize: Maximize,
  menu: Menu,
  minus: Minus,
  minimize: Minimize,
  moon: Moon,
  package: Package,
  mail: Mail,
  'package-plus': PackagePlus,
  'package-search': PackageSearch,
  pen: Pen,
  phone: Phone,
  plus: Plus,
  play: Play,
  printer: Printer,
  'refresh-cw': RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  share: Share2,
  'shield-check': ShieldCheck,
  'shopping-cart': ShoppingCart,
  'file-text': FileText,
  book: BookOpen,
  mic: Mic,
  star: Star,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  sun: Sun,
  tag: Tag,
  thermometer: Thermometer,
  upload: Upload,
  trash: Trash2,
  truck: Truck,
  twitter: Twitter,
  user: User,
  whatsapp: MessageCircle,
  x: X,
  youtube: Youtube,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  list: List,
  gift: Gift,
  sparkles: Sparkles,
  'refresh-ccw': RefreshCcw,
  users: Users,
  download: Download,
  'smartphone': Smartphone,
  'wifi-off': WifiOff,
  zap: Zap,
  'message-circle': MessageCircle,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconRegistry;

export type IconProps = Omit<LucideProps, 'size'> & {
  name: IconName;
  size?: Size | number;
  flipRtl?: boolean;
  className?: string;
  'aria-label'?: string;
};

export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
  { name, size = 'md', className, flipRtl = false, 'aria-hidden': ariaHidden, 'aria-label': ariaLabel, ...props },
  ref
) {
  const locale = useLocale();
  const IconComponent = iconRegistry[name] ?? HelpCircle;
  const resolvedSize =
    typeof size === 'number' ? size : ICON_SIZES[size] ?? ICON_SIZES.md;

  return (
    <IconComponent
      ref={ref}
      size={resolvedSize}
      className={cn(
        flipRtl && locale === 'ar' && 'rtl-flip',
        className
      )}
      aria-hidden={ariaHidden ?? !ariaLabel}
      aria-label={ariaLabel}
      {...props}
    />
  );
});
